#File to hold program constants

MESSAGE_TYPES = {
    "ENROLLMENT":1,
    "KICKOFF":2,
    "PROGRAM_START":2,
    "APPOINTMENT_REMINDER":4,
    "MEETING_REMINDER":5,
    "BIRTHDAY":6,

}

VENUE = "Wellness Offices"

ENROLLMENT_TYPE_ID = 1
KICKOFF_TYPE_ID = 2
BIRTHDAY_TYPE_ID = 3
APPOINTMENT_REMINDER_TYPE_ID = 4
